# Generated by Django 3.0.7 on 2020-06-05 10:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('colors', multiselectfield.db.fields.MultiSelectField(choices=[('blue', 'blue'), ('red', 'red'), ('yellow', 'yellow')], max_length=15)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=5)),
            ],
        ),
    ]
